import type { EventMessage } from '../game/types';

export const EVENTS: EventMessage[] = [
  { id: 'e1', text: '> System online. Void interface initialized.', unlockAt: 0, category: 'system' },
  { id: 'e2', text: '> First flux detected. It tastes like static.', unlockAt: 10, category: 'log' },
  { id: 'e3', text: '> The antenna picks up a faint signal: "...hello...?"', unlockAt: 100, category: 'discovery' },
  { id: 'e4', text: '> Condenser operational. The void seems slightly annoyed.', unlockAt: 200, category: 'system' },
  { id: 'e5', text: '> A data fragment materializes: "DO NOT LOOK BEHIND THE FREQUENCY"', unlockAt: 500, category: 'anomaly' },
  { id: 'e6', text: '> Production exceeds initial estimates by 340%. Nobody set initial estimates.', unlockAt: 1000, category: 'log' },
  { id: 'e7', text: '> Harvester calibrated. The deep frequencies are... musical?', unlockAt: 3000, category: 'system' },
  { id: 'e8', text: '> Log entry: "Day 47. The machine hums. I hum back. We understand each other."', unlockAt: 5000, category: 'log' },
  { id: 'e9', text: '> ANOMALY: Brief gravitational hiccup. Coffee floated for 3 seconds.', unlockAt: 10000, category: 'anomaly' },
  { id: 'e10', text: '> Research module coming online. Knowledge is power. Literally, in this case.', unlockAt: 15000, category: 'system' },
  { id: 'e11', text: '> Signal decoded: "WE HAVE BEEN TRYING TO REACH YOU ABOUT YOUR VOID\'S EXTENDED WARRANTY"', unlockAt: 25000, category: 'discovery' },
  { id: 'e12', text: '> The quantum refinery produces a perfectly cubic crystal. Then it produces an apology.', unlockAt: 50000, category: 'log' },
  { id: 'e13', text: '> ANOMALY: Local time briefly ran backwards. Tuesday happened twice.', unlockAt: 100000, category: 'anomaly' },
  { id: 'e14', text: '> Phase Array synchronization complete. Reality reception: 5 bars.', unlockAt: 200000, category: 'system' },
  { id: 'e15', text: '> A small void creature appears, waves, and dissolves. You wave back too slowly.', unlockAt: 500000, category: 'discovery' },
  { id: 'e16', text: '> MILESTONE: One million flux processed. The void sends a fruit basket.', unlockAt: 1000000, category: 'log' },
  { id: 'e17', text: '> Singularity Tap engaged. HR wants to know if this counts as a workplace hazard.', unlockAt: 2000000, category: 'system' },
  { id: 'e18', text: '> ANOMALY: The machine briefly became self-aware. It asked for a raise.', unlockAt: 5000000, category: 'anomaly' },
  { id: 'e19', text: '> Dimensional Rift opened. Something on the other side left a Yelp review: ★★★☆☆', unlockAt: 10000000, category: 'discovery' },
  { id: 'e20', text: '> Log entry: "The void is not empty. It\'s just very, very patient."', unlockAt: 25000000, category: 'log' },
  { id: 'e21', text: '> ANOMALY: Entropy briefly reversed. Your coffee un-spilled. Still tasted bad.', unlockAt: 50000000, category: 'anomaly' },
  { id: 'e22', text: '> Beacon signal received: "YOU ARE HERE ←" (helpful)', unlockAt: 100000000, category: 'discovery' },
  { id: 'e23', text: '> The Entropy Weaver produces a philosophical treatise. It\'s surprisingly good.', unlockAt: 500000000, category: 'log' },
  { id: 'e24', text: '> ANOMALY: The Temporal Oracle predicts the past. Accurately. Uselessly.', unlockAt: 1000000000, category: 'anomaly' },
  { id: 'e25', text: '> Reality Architect constructs a pocket universe. It immediately demands independence.', unlockAt: 5000000000, category: 'discovery' },
  { id: 'e26', text: '> The God Engine awakens. It yawns. The yawn creates three new galaxies.', unlockAt: 10000000000, category: 'system' },
  { id: 'e27', text: '> Final log: "We didn\'t find the void. The void found us. It seems pleased."', unlockAt: 50000000000, category: 'log' },
  { id: 'e28', text: '> ECHO DETECTED: Time folds. Your past self waves. You pretend not to see.', unlockAt: 0, category: 'system' },
];
