import type { ExpeditionZoneDef, ExpeditionArtifactDef, ExpeditionLoreDef } from '../game/types';

export const EXPEDITION_ZONES: ExpeditionZoneDef[] = [
  {
    id: 'shallow_void',
    name: 'Shallow Void',
    description: 'The outermost layer of the void. Relatively safe, but rewards are modest.',
    flavorText: 'The void whispers here, but it does not bite.',
    difficulty: 500,
    minDuration: 60,
    maxDuration: 300,
    unlockCondition: { type: 'flux', value: 100_000 },
    rewardTable: [
      { id: 'sv_flux', type: 'flux', probability: 1.0, amountRange: [30, 120], scaling: 'production_based' },
      { id: 'sv_data', type: 'data', probability: 0.3, amountRange: [500, 2000], scaling: 'flat' },
      { id: 'sv_boost', type: 'temp_boost', probability: 0.15, amountRange: [2, 2], scaling: 'flat' },
      { id: 'sv_artifact', type: 'artifact', probability: 0.15, amountRange: [1, 1], scaling: 'flat' },
    ],
    eventPool: [
      { id: 'sv_e1', text: 'Your Void Antennas detected a faint signal in the static...', effect: 'flavor', value: 0, probability: 0.3 },
      { id: 'sv_e2', text: 'A data cache was discovered! Bonus data incoming.', effect: 'bonus_reward', value: 0.2, probability: 0.15 },
      { id: 'sv_e3', text: 'Void turbulence reduced expedition efficiency briefly.', effect: 'power_penalty', value: 0.05, probability: 0.1 },
      { id: 'sv_e4', text: 'A resonance pocket amplified your generators temporarily!', effect: 'power_bonus', value: 0.1, probability: 0.1 },
    ],
  },
  {
    id: 'data_nebula',
    name: 'Data Nebula',
    description: 'Dense clouds of encoded void data. Rich in information, treacherous to navigate.',
    flavorText: 'Every particle here carries a fragment of forgotten knowledge.',
    difficulty: 5000,
    minDuration: 120,
    maxDuration: 600,
    unlockCondition: { type: 'flux', value: 1_000_000 },
    rewardTable: [
      { id: 'dn_flux', type: 'flux', probability: 1.0, amountRange: [60, 180], scaling: 'production_based' },
      { id: 'dn_data', type: 'data', probability: 0.6, amountRange: [2000, 8000], scaling: 'flat' },
      { id: 'dn_lore', type: 'lore', probability: 0.2, amountRange: [1, 1], scaling: 'flat' },
      { id: 'dn_artifact', type: 'artifact', probability: 0.15, amountRange: [1, 1], scaling: 'flat' },
    ],
    eventPool: [
      { id: 'dn_e1', text: 'The nebula shifts, revealing hidden data streams...', effect: 'bonus_reward', value: 0.25, probability: 0.2 },
      { id: 'dn_e2', text: 'Electromagnetic interference scrambled your readings.', effect: 'power_penalty', value: 0.1, probability: 0.12 },
      { id: 'dn_e3', text: 'Your scanners picked up an ancient transmission.', effect: 'flavor', value: 0, probability: 0.25 },
    ],
  },
  {
    id: 'echo_caverns',
    name: 'Echo Caverns',
    description: 'Vast chambers where echoes of past realities linger. The walls remember everything.',
    flavorText: 'Here, time has already happened. You are just visiting the aftermath.',
    difficulty: 25000,
    minDuration: 300,
    maxDuration: 1200,
    unlockCondition: { type: 'prestige', value: 1 },
    rewardTable: [
      { id: 'ec_flux', type: 'flux', probability: 1.0, amountRange: [120, 360], scaling: 'production_based' },
      { id: 'ec_echoes', type: 'echoes', probability: 0.25, amountRange: [1, 3], scaling: 'flat' },
      { id: 'ec_lore', type: 'lore', probability: 0.3, amountRange: [1, 1], scaling: 'flat' },
      { id: 'ec_artifact', type: 'artifact', probability: 0.18, amountRange: [1, 1], scaling: 'flat' },
    ],
    eventPool: [
      { id: 'ec_e1', text: 'An echo of a past explorer guides your path forward.', effect: 'power_bonus', value: 0.15, probability: 0.15 },
      { id: 'ec_e2', text: 'The cavern walls collapsed, trapping some generators temporarily!', effect: 'power_penalty', value: 0.15, probability: 0.1 },
      { id: 'ec_e3', text: 'You found the preserved echo of a forgotten universe.', effect: 'flavor', value: 0, probability: 0.2 },
    ],
  },
  {
    id: 'quantum_fields',
    name: 'Quantum Fields',
    description: 'Reality becomes probabilistic here. Every outcome exists simultaneously.',
    flavorText: 'Are you observing the void, or is the void observing you?',
    difficulty: 150000,
    minDuration: 600,
    maxDuration: 2400,
    unlockCondition: { type: 'prestige', value: 10 },
    rewardTable: [
      { id: 'qf_flux', type: 'flux', probability: 1.0, amountRange: [240, 600], scaling: 'production_based' },
      { id: 'qf_data', type: 'data', probability: 0.4, amountRange: [5000, 20000], scaling: 'flat' },
      { id: 'qf_echoes', type: 'echoes', probability: 0.2, amountRange: [2, 5], scaling: 'flat' },
      { id: 'qf_perm', type: 'permanent_bonus', probability: 0.08, amountRange: [1, 3], scaling: 'flat' },
      { id: 'qf_artifact', type: 'artifact', probability: 0.20, amountRange: [1, 1], scaling: 'flat' },
    ],
    eventPool: [
      { id: 'qf_e1', text: 'Quantum superposition collapsed in your favor!', effect: 'power_bonus', value: 0.2, probability: 0.15 },
      { id: 'qf_e2', text: 'Reality flickered. Some generators phased out temporarily.', effect: 'power_penalty', value: 0.1, probability: 0.12 },
      { id: 'qf_e3', text: 'You observed a probability wave that should not exist.', effect: 'flavor', value: 0, probability: 0.2 },
    ],
  },
  {
    id: 'deep_void',
    name: 'The Deep Void',
    description: 'The space between spaces. Nothing should exist here, yet something does.',
    flavorText: 'Beyond the dark, past the nothing, lies something that hungers.',
    difficulty: 1000000,
    minDuration: 1200,
    maxDuration: 3600,
    unlockCondition: { type: 'prestige', value: 50 },
    rewardTable: [
      { id: 'dv_flux', type: 'flux', probability: 1.0, amountRange: [480, 1200], scaling: 'production_based' },
      { id: 'dv_echoes', type: 'echoes', probability: 0.4, amountRange: [3, 8], scaling: 'flat' },
      { id: 'dv_perm', type: 'permanent_bonus', probability: 0.1, amountRange: [2, 5], scaling: 'flat' },
      { id: 'dv_artifact', type: 'artifact', probability: 0.25, amountRange: [1, 1], scaling: 'flat' },
      { id: 'dv_lore', type: 'lore', probability: 0.25, amountRange: [1, 1], scaling: 'flat' },
    ],
    eventPool: [
      { id: 'dv_e1', text: 'Something massive moved in the deep void. Your generators are energized!', effect: 'power_bonus', value: 0.25, probability: 0.12 },
      { id: 'dv_e2', text: 'The void consumed some of your expedition power.', effect: 'power_penalty', value: 0.15, probability: 0.1 },
      { id: 'dv_e3', text: 'You found a message carved into nothing itself.', effect: 'flavor', value: 0, probability: 0.2 },
    ],
  },
];

export const EXPEDITION_ARTIFACTS: ExpeditionArtifactDef[] = [
  {
    id: 'void_compass',
    name: 'Void Compass',
    description: '+10% expedition reward quality',
    effect: 'reward_quality',
    zoneId: 'shallow_void',
    icon: '🧭',
  },
  {
    id: 'data_scanner',
    name: 'Data Scanner',
    description: '+25% data from expeditions',
    effect: 'data_bonus',
    zoneId: 'data_nebula',
    icon: '📡',
  },
  {
    id: 'echo_resonator',
    name: 'Echo Resonator',
    description: '+10% echo gain globally',
    effect: 'echo_bonus',
    zoneId: 'echo_caverns',
    icon: '🔮',
  },
  {
    id: 'quantum_stabilizer',
    name: 'Quantum Stabilizer',
    description: '-10% generator cost',
    effect: 'cost_reduction',
    zoneId: 'quantum_fields',
    icon: '⚛️',
  },
  {
    id: 'void_heart',
    name: 'Void Heart',
    description: '+1% all production per expedition completed',
    effect: 'production_per_expedition',
    zoneId: 'deep_void',
    icon: '💜',
  },
];

export const EXPEDITION_LORE: ExpeditionLoreDef[] = [
  { id: 'lore_1', text: 'The void was not always empty. Once, it was everything.', zoneId: 'shallow_void' },
  { id: 'lore_2', text: 'Data does not decay in the void. It transforms.', zoneId: 'data_nebula' },
  { id: 'lore_3', text: 'The first explorers never returned. Their echoes still search.', zoneId: 'echo_caverns' },
  { id: 'lore_4', text: 'In quantum fields, every choice creates a universe. Most die instantly.', zoneId: 'quantum_fields' },
  { id: 'lore_5', text: 'Something built the void. Something lives within.', zoneId: 'deep_void' },
  { id: 'lore_6', text: 'The void remembers every expedition. It is learning from you.', zoneId: 'data_nebula' },
  { id: 'lore_7', text: 'Echoes are not memories. They are warnings.', zoneId: 'echo_caverns' },
  { id: 'lore_8', text: 'The deeper you go, the more the void resembles a mind.', zoneId: 'deep_void' },
  { id: 'lore_9', text: 'Before flux, there was silence. Before silence, there was a scream.', zoneId: 'shallow_void' },
  { id: 'lore_10', text: 'Quantum stabilization is an illusion. The fields want you to think you are in control.', zoneId: 'quantum_fields' },
];
