import type { GeneratorDef } from '../game/types';

export const GENERATORS: GeneratorDef[] = [
  {
    id: 'antenna',
    name: 'Void Antenna',
    description: 'Catches faint whispers of flux drifting through subspace.',
    baseCost: 15,
    costGrowth: 1.15,
    baseProduction: 0.3,
    unlockAt: 0,
    tier: 1,
  },
  {
    id: 'condenser',
    name: 'Flux Condenser',
    description: 'Compresses ambient void energy into usable flux packets.',
    baseCost: 120,
    costGrowth: 1.16,
    baseProduction: 2,
    unlockAt: 75,
    tier: 1,
  },
  {
    id: 'harvester',
    name: 'Resonance Harvester',
    description: 'Tunes into deep-frequency void oscillations for sustained flux yield.',
    baseCost: 750,
    costGrowth: 1.17,
    baseProduction: 9,
    unlockAt: 500,
    tier: 2,
  },
  {
    id: 'refinery',
    name: 'Quantum Refinery',
    description: 'Distills raw void noise into pure, concentrated flux streams.',
    baseCost: 4500,
    costGrowth: 1.17,
    baseProduction: 35,
    unlockAt: 3000,
    tier: 2,
  },
  {
    id: 'array',
    name: 'Phase Array',
    description: 'A coordinated grid of receivers that amplifies weak signals exponentially.',
    baseCost: 15000,
    costGrowth: 1.17,
    baseProduction: 160,
    unlockAt: 12000,
    tier: 3,
  },
  {
    id: 'singularity',
    name: 'Singularity Tap',
    description: 'Siphons flux directly from a stabilized micro-singularity. Probably safe.',
    baseCost: 80000,
    costGrowth: 1.18,
    baseProduction: 550,
    unlockAt: 60000,
    tier: 3,
  },
  {
    id: 'rift',
    name: 'Dimensional Rift',
    description: 'A controlled tear in spacetime. The flux pours in. So does the weird.',
    baseCost: 500000,
    costGrowth: 1.19,
    baseProduction: 1800,
    unlockAt: 300000,
    tier: 4,
  },
  {
    id: 'beacon',
    name: 'Void Beacon',
    description: 'Broadcasts your presence into the void. Something always answers.',
    baseCost: 3000000,
    costGrowth: 1.20,
    baseProduction: 6000,
    unlockAt: 1500000,
    tier: 4,
  },
  {
    id: 'weaver',
    name: 'Entropy Weaver',
    description: 'Knits disorder itself into structured flux. Thermodynamics hates this.',
    baseCost: 20000000,
    costGrowth: 1.18,
    baseProduction: 20000,
    unlockAt: 8000000,
    tier: 5,
  },
  {
    id: 'oracle',
    name: 'Temporal Oracle',
    description: 'Harvests flux from futures that never happen. Ethically ambiguous.',
    baseCost: 150000000,
    costGrowth: 1.19,
    baseProduction: 70000,
    unlockAt: 50000000,
    tier: 5,
  },
  {
    id: 'architect',
    name: 'Reality Architect',
    description: 'Constructs pocket universes optimized for maximum flux output.',
    baseCost: 1200000000,
    costGrowth: 1.20,
    baseProduction: 250000,
    unlockAt: 400000000,
    tier: 6,
  },
  {
    id: 'godengine',
    name: 'The God Engine',
    description: 'You are no longer harvesting flux. You are generating reality.',
    baseCost: 10000000000,
    costGrowth: 1.21,
    baseProduction: 1000000,
    unlockAt: 3000000000,
    tier: 6,
  },
];
