import type { PrestigeUpgradeDef } from '../game/types';

export const PRESTIGE_UPGRADES: PrestigeUpgradeDef[] = [
  {
    id: 'p_production1',
    name: 'Residual Vibrations',
    description: 'All production x1.3 per level.',
    cost: 2,
    maxLevel: 8,
    effect: { type: 'productionMultiplier', value: 1.3 },
  },
  {
    id: 'p_startflux',
    name: 'Flux Memory',
    description: 'Start each run with 500 × level flux.',
    cost: 2,
    maxLevel: 8,
    effect: { type: 'startingFlux', value: 500 },
  },
  {
    id: 'p_clickpower',
    name: 'Echo Click',
    description: 'Click power x1.3 per level.',
    cost: 3,
    maxLevel: 5,
    effect: { type: 'clickPower', value: 1.3 },
  },
  {
    id: 'p_costreduce',
    name: 'Efficient Memories',
    description: 'All generator costs reduced by 4% per level.',
    cost: 3,
    maxLevel: 5,
    effect: { type: 'costReduction', value: 0.04 },
  },
  {
    id: 'p_offline',
    name: 'Dream Echoes',
    description: 'Offline efficiency +8% per level.',
    cost: 4,
    maxLevel: 5,
    effect: { type: 'offlineBonus', value: 0.08 },
  },
  {
    id: 'p_echogain',
    name: 'Resonant Feedback',
    description: '+12% echo gain per level.',
    cost: 5,
    maxLevel: 7,
    effect: { type: 'echoGainBonus', value: 0.12 },
  },
  {
    id: 'p_production2',
    name: 'Harmonic Convergence',
    description: 'All production x1.6 per level.',
    cost: 8,
    maxLevel: 5,
    effect: { type: 'productionMultiplier', value: 1.6 },
  },
  {
    id: 'p_startflux2',
    name: 'Imprinted Wealth',
    description: 'Start each run with 15000 × level flux.',
    cost: 6,
    maxLevel: 5,
    effect: { type: 'startingFlux', value: 15000 },
  },
  {
    id: 'p_clickpower2',
    name: 'Phantom Fingers',
    description: 'Click power x1.6 per level.',
    cost: 12,
    maxLevel: 3,
    effect: { type: 'clickPower', value: 1.6 },
  },
  {
    id: 'p_production3',
    name: 'Void Mastery',
    description: 'All production x2 per level.',
    cost: 20,
    maxLevel: 3,
    effect: { type: 'productionMultiplier', value: 2 },
  },
  {
    id: 'p_datarate',
    name: 'Data Resonance',
    description: 'Data generation +20% per level.',
    cost: 3,
    maxLevel: 5,
    effect: { type: 'dataRateBonus', value: 0.2 },
  },
  {
    id: 'p_researchspeed',
    name: 'Temporal Research',
    description: 'Research speed +20% per level.',
    cost: 4,
    maxLevel: 5,
    effect: { type: 'researchSpeedBonus', value: 0.2 },
  },
  {
    id: 'p_researchtap',
    name: 'Echo Accelerator',
    description: 'Research smash power +35% per level.',
    cost: 3,
    maxLevel: 5,
    effect: { type: 'researchTapBonus', value: 0.35 },
  },
  {
    id: 'p_riftfreq',
    name: 'Rift Attractor',
    description: 'Void rifts appear 15% more often per level.',
    cost: 6,
    maxLevel: 3,
    effect: { type: 'riftFrequency', value: 0.15 },
  },
  {
    id: 'p_premium_bonus',
    name: 'Patron\'s Echo',
    description: 'All production x1.08 per level. Supporter exclusive.',
    cost: 2,
    maxLevel: 3,
    effect: { type: 'productionMultiplier', value: 1.08 },
  },
];
