import type { ResearchNodeDef } from '../game/types';

export const RESEARCH_NODES: ResearchNodeDef[] = [
  // ─── Branch 1: Production Mastery ───
  {
    id: 'r_basics',
    name: 'Void Theory 101',
    description: 'Understand the basics. All production +10%.',
    cost: 50,
    costResource: 'data',
    duration: 30,
    unlockAt: 10000,
    effect: { type: 'globalMultiplier', value: 1.1 },
    flavorText: 'Chapter 1: "Don\'t look directly at the void."',
  },
  {
    id: 'r_power_analysis',
    name: 'Power Distribution Analysis',
    description: 'Shows each generator\'s % contribution to total flux.',
    cost: 30,
    costResource: 'data',
    duration: 20,
    unlockAt: 5000,
    effect: { type: 'unlockAnalytics', value: 1 },
    flavorText: 'Knowledge is power. Literally—it shows you where the power is.',
  },
  {
    id: 'r_upgrade_forecast',
    name: 'Predictive Modeling',
    description: 'Shows projected % gain when hovering upgrade buttons.',
    cost: 80,
    costResource: 'data',
    duration: 25,
    unlockAt: 15000,
    requires: ['r_power_analysis'],
    effect: { type: 'unlockAnalytics', value: 2 },
    flavorText: 'See the future. Specifically, the boring spreadsheet version of it.',
  },
  {
    id: 'r_efficiency',
    name: 'Thermal Regulation',
    description: 'All production +15%.',
    cost: 150,
    costResource: 'data',
    duration: 60,
    unlockAt: 50000,
    requires: ['r_basics'],
    effect: { type: 'globalMultiplier', value: 1.15 },
    flavorText: 'The machine was running hot. Now it runs warm. Progress.',
  },
  {
    id: 'r_clicking',
    name: 'Haptic Feedback Loop',
    description: 'Click power x2.',
    cost: 200,
    costResource: 'data',
    duration: 40,
    unlockAt: 30000,
    requires: ['r_basics'],
    effect: { type: 'clickMultiplier', value: 2 },
  },
  {
    id: 'r_deepvoid',
    name: 'Deep Void Cartography',
    description: 'All production +25%.',
    cost: 400,
    costResource: 'data',
    duration: 90,
    unlockAt: 200000,
    requires: ['r_efficiency'],
    effect: { type: 'globalMultiplier', value: 1.25 },
    flavorText: 'Mapping the unmappable. It mostly works.',
  },
  {
    id: 'r_overclock',
    name: 'Controlled Overclock',
    description: 'All production +30%.',
    cost: 800,
    costResource: 'data',
    duration: 120,
    unlockAt: 500000,
    requires: ['r_deepvoid'],
    effect: { type: 'globalMultiplier', value: 1.3 },
    flavorText: 'Push it past the red line. It\'s fine. Probably.',
  },
  {
    id: 'r_quantum',
    name: 'Quantum Entanglement',
    description: 'All production +40%.',
    cost: 1500,
    costResource: 'data',
    duration: 150,
    unlockAt: 2000000,
    requires: ['r_overclock'],
    effect: { type: 'globalMultiplier', value: 1.4 },
  },
  // NEW: Production branch — Generator Optimization
  {
    id: 'r_genoptimize',
    name: 'Generator Optimization',
    description: 'All generator costs reduced by 10%.',
    cost: 500,
    costResource: 'data',
    duration: 80,
    unlockAt: 300000,
    requires: ['r_deepvoid'],
    effect: { type: 'globalMultiplier', value: 1.1 },
    flavorText: 'Squeeze more from less. The engineer\'s creed.',
  },
  // NEW: Production branch — Mass Production
  {
    id: 'r_massproduction',
    name: 'Mass Production',
    description: 'All production +20%. Synergizes with generator count.',
    cost: 2000,
    costResource: 'data',
    duration: 160,
    unlockAt: 5000000,
    requires: ['r_genoptimize'],
    effect: { type: 'globalMultiplier', value: 1.2 },
    flavorText: 'More is more. Sometimes the simple answer is the right one.',
  },
  // NEW: Production branch — Efficiency Matrix
  {
    id: 'r_effmatrix',
    name: 'Efficiency Matrix',
    description: 'All production +15%. Bonus per milestone reached.',
    cost: 3000,
    costResource: 'data',
    duration: 200,
    unlockAt: 10000000,
    requires: ['r_quantum'],
    effect: { type: 'globalMultiplier', value: 1.15 },
    flavorText: 'The matrix hums with optimized potential.',
  },

  // ─── Branch 2: Data Sciences ───
  {
    id: 'r_signals',
    name: 'Signal Decryption',
    description: 'Data generation rate +25%.',
    cost: 100,
    costResource: 'data',
    duration: 45,
    unlockAt: 25000,
    requires: ['r_basics'],
    effect: { type: 'dataRate', value: 0.25 },
    flavorText: 'Most signals are just void static. Some are not.',
  },
  {
    id: 'r_datasurge',
    name: 'Data Surge Protocol',
    description: 'Data generation rate +50%.',
    cost: 600,
    costResource: 'data',
    duration: 75,
    unlockAt: 300000,
    requires: ['r_signals'],
    effect: { type: 'dataRate', value: 0.5 },
  },
  {
    id: 'r_datastream',
    name: 'Perpetual Data Stream',
    description: 'Data generation rate +100%.',
    cost: 4000,
    costResource: 'data',
    duration: 240,
    unlockAt: 20000000,
    requires: ['r_datasurge'],
    effect: { type: 'dataRate', value: 1.0 },
    flavorText: 'The data never stops. Neither does the machine.',
  },
  // NEW: Data branch — Pattern Analysis
  {
    id: 'r_patterns',
    name: 'Pattern Analysis',
    description: 'Data rate +30%. Data scales with generator count.',
    cost: 1200,
    costResource: 'data',
    duration: 100,
    unlockAt: 1000000,
    requires: ['r_datasurge'],
    effect: { type: 'dataRate', value: 0.3 },
    flavorText: 'Patterns within patterns. The void is speaking in code.',
  },
  // NEW: Data branch — Data Compression
  {
    id: 'r_datacompress',
    name: 'Data Compression II',
    description: 'Data rate +40%. More efficient data storage.',
    cost: 6000,
    costResource: 'data',
    duration: 280,
    unlockAt: 30000000,
    requires: ['r_datastream'],
    effect: { type: 'dataRate', value: 0.4 },
    flavorText: 'Compress the incompressible. It\'s data all the way down.',
  },
  // NEW: Data branch — Data Mining
  {
    id: 'r_datamining',
    name: 'Data Mining Protocols',
    description: 'Data rate +25%. Clicking generates data.',
    cost: 800,
    costResource: 'data',
    duration: 90,
    unlockAt: 500000,
    requires: ['r_signals'],
    effect: { type: 'dataRate', value: 0.25 },
    flavorText: 'Dig deeper. There\'s always more data to find.',
  },

  // ─── Branch 4: Prestige & Meta ───
  {
    id: 'r_prestige_theory',
    name: 'Echo Theory',
    description: 'Unlocks the Echo Chamber (prestige system).',
    cost: 1000,
    costResource: 'data',
    duration: 180,
    unlockAt: 1000000,
    requires: ['r_deepvoid'],
    effect: { type: 'unlockSystem', value: 1 },
    flavorText: 'What if you could start over, but remember everything?',
  },
  {
    id: 'r_anomaly',
    name: 'Anomaly Studies',
    description: 'All production +20%.',
    cost: 2000,
    costResource: 'data',
    duration: 120,
    unlockAt: 5000000,
    requires: ['r_quantum'],
    effect: { type: 'globalMultiplier', value: 1.2 },
    flavorText: 'The anomalies study you back.',
  },
  {
    id: 'r_prestige_boost',
    name: 'Echo Amplification',
    description: '+25% echo gain on prestige.',
    cost: 3000,
    costResource: 'data',
    duration: 200,
    unlockAt: 10000000,
    requires: ['r_prestige_theory'],
    effect: { type: 'prestigeBonus', value: 0.25 },
  },
  {
    id: 'r_hypervoid',
    name: 'Hypervoid Access',
    description: 'All production x2.',
    cost: 5000,
    costResource: 'data',
    duration: 300,
    unlockAt: 50000000,
    requires: ['r_anomaly'],
    effect: { type: 'globalMultiplier', value: 2 },
    flavorText: 'Beyond the void is another void. It\'s voids all the way down.',
  },
  {
    id: 'r_infinity',
    name: 'Infinity Calculus',
    description: 'All production x3.',
    cost: 10000,
    costResource: 'data',
    duration: 600,
    unlockAt: 100000000,
    requires: ['r_hypervoid'],
    effect: { type: 'globalMultiplier', value: 3 },
    flavorText: 'Division by zero? More like multiplication by infinity.',
  },
  {
    id: 'r_clickmaster',
    name: 'Digital Ascension',
    description: 'Click power x5.',
    cost: 8000,
    costResource: 'data',
    duration: 180,
    unlockAt: 100000000,
    requires: ['r_clicking', 'r_quantum'],
    effect: { type: 'clickMultiplier', value: 5 },
    flavorText: 'Your finger transcends physical form.',
  },
  {
    id: 'r_echo_mastery',
    name: 'Echo Mastery',
    description: '+50% echo gain on prestige.',
    cost: 15000,
    costResource: 'data',
    duration: 400,
    unlockAt: 200000000,
    requires: ['r_prestige_boost', 'r_infinity'],
    effect: { type: 'prestigeBonus', value: 0.5 },
    flavorText: 'The echoes echo. It\'s getting loud in here.',
  },
  // NEW: Prestige branch — Echo Recursion
  {
    id: 'r_echo_recursion',
    name: 'Echo Recursion',
    description: '+20% echo gain. Echoes scale with prestige count.',
    cost: 20000,
    costResource: 'data',
    duration: 450,
    unlockAt: 2000000000,
    requires: ['r_echo_mastery'],
    effect: { type: 'prestigeBonus', value: 0.2 },
    flavorText: 'Echoes of echoes of echoes. The recursion never ends.',
  },
  // NEW: Prestige branch — Rift Attunement
  {
    id: 'r_rift_attunement',
    name: 'Rift Attunement',
    description: 'All production +25%. Attuned to void rifts.',
    cost: 4000,
    costResource: 'data',
    duration: 180,
    unlockAt: 20000000,
    requires: ['r_anomaly'],
    effect: { type: 'globalMultiplier', value: 1.25 },
    flavorText: 'The rifts respond to your presence now.',
  },
  // NEW: Prestige branch — Event Horizon
  {
    id: 'r_event_horizon',
    name: 'Event Horizon',
    description: 'All production +20%. Events last longer.',
    cost: 6000,
    costResource: 'data',
    duration: 250,
    unlockAt: 50000000,
    requires: ['r_rift_attunement'],
    effect: { type: 'globalMultiplier', value: 1.2 },
    flavorText: 'Time dilates at the edge. Effects linger.',
  },
  // NEW: Prestige branch — Void Collapse Theory
  {
    id: 'r_void_collapse',
    name: 'Void Collapse Theory',
    description: 'Unlocks the Void Collapse (second prestige layer).',
    cost: 15000,
    costResource: 'data',
    duration: 300,
    unlockAt: 500000000,
    requires: ['r_echo_mastery'],
    effect: { type: 'unlockSystem', value: 2 },
    flavorText: 'Beyond the echo lies the collapse. Everything resets... deeper.',
  },
  // NEW: Synergy branch — Void Resonance Theory
  {
    id: 'r_resonance',
    name: 'Void Resonance Theory',
    description: 'All production +10%. Generators resonate together.',
    cost: 1000,
    costResource: 'data',
    duration: 120,
    unlockAt: 2000000,
    requires: ['r_overclock'],
    effect: { type: 'globalMultiplier', value: 1.1 },
    flavorText: 'When frequencies align, power multiplies.',
  },
  // NEW: Synergy branch — Harmonic Coupling
  {
    id: 'r_harmonic',
    name: 'Harmonic Coupling',
    description: 'All production +20%. Enhanced synergy effects.',
    cost: 3000,
    costResource: 'data',
    duration: 200,
    unlockAt: 10000000,
    requires: ['r_resonance'],
    effect: { type: 'globalMultiplier', value: 1.2 },
    flavorText: 'The harmonics reach a crescendo.',
  },
  // NEW: Synergy branch — Perfect Resonance
  {
    id: 'r_perfect_resonance',
    name: 'Perfect Resonance',
    description: 'All production x1.5. Maximum harmonic potential.',
    cost: 8000,
    costResource: 'data',
    duration: 350,
    unlockAt: 100000000,
    requires: ['r_harmonic'],
    effect: { type: 'globalMultiplier', value: 1.5 },
    flavorText: 'Perfect harmony. Every generator sings as one.',
  },
];
