import type { UpgradeDef } from '../game/types';

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'click1',
    name: 'Sharper Focus',
    description: '+1 flux per click.',
    cost: 100,
    costResource: 'flux',
    unlockAt: 40,
    effect: { type: 'clickFlat', value: 1 },
    maxLevel: 1,
    flavorText: 'You learn to squint at the void more productively.',
  },
  {
    id: 'click2',
    name: 'Neural Tap',
    description: '+3 flux per click.',
    cost: 800,
    costResource: 'flux',
    unlockAt: 350,
    effect: { type: 'clickFlat', value: 3 },
    maxLevel: 1,
    flavorText: 'Your thoughts now directly irritate the void.',
  },
  {
    id: 'click3',
    name: 'Synapse Overclock',
    description: 'x2 click power.',
    cost: 7500,
    costResource: 'flux',
    unlockAt: 3000,
    effect: { type: 'clickMultiplier', value: 2 },
    maxLevel: 1,
    flavorText: 'Side effects include mild temporal echoes.',
  },
  {
    id: 'click4',
    name: 'Quantum Finger',
    description: '+10 flux per click.',
    cost: 50000,
    costResource: 'flux',
    unlockAt: 20000,
    effect: { type: 'clickFlat', value: 10 },
    maxLevel: 1,
  },
  {
    id: 'click5',
    name: 'Resonance Tap',
    description: 'Clicks gain +5% of flux/sec.',
    cost: 100000,
    costResource: 'flux',
    unlockAt: 50000,
    effect: { type: 'clickPercent', value: 0.05 },
    maxLevel: 3,
    flavorText: 'Your clicks now echo through the generators.',
  },
  {
    id: 'click6',
    name: 'Void Siphon',
    description: 'Clicks gain +10% of flux/sec.',
    cost: 5000000,
    costResource: 'flux',
    unlockAt: 1000000,
    effect: { type: 'clickPercent', value: 0.1 },
    maxLevel: 3,
    flavorText: 'Each click tears a tiny hole in reality. Flux pours out.',
  },
  {
    id: 'antenna_boost',
    name: 'Antenna Calibration',
    description: 'Void Antennas produce x2.',
    cost: 350,
    costResource: 'flux',
    unlockAt: 150,
    effect: { type: 'generatorMultiplier', targetId: 'antenna', value: 2 },
    maxLevel: 1,
    flavorText: 'Slight twist to the left. There.',
  },
  {
    id: 'condenser_boost',
    name: 'Pressure Upgrade',
    description: 'Flux Condensers produce x2.',
    cost: 2500,
    costResource: 'flux',
    unlockAt: 800,
    effect: { type: 'generatorMultiplier', targetId: 'condenser', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'harvester_boost',
    name: 'Deep Frequency Tuning',
    description: 'Resonance Harvesters produce x2.',
    cost: 12000,
    costResource: 'flux',
    unlockAt: 5000,
    effect: { type: 'generatorMultiplier', targetId: 'harvester', value: 2 },
    maxLevel: 1,
    flavorText: 'The void hums at 42 Hz. Coincidence?',
  },
  {
    id: 'refinery_boost',
    name: 'Catalytic Injection',
    description: 'Quantum Refineries produce x2.',
    cost: 60000,
    costResource: 'flux',
    unlockAt: 25000,
    effect: { type: 'generatorMultiplier', targetId: 'refinery', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'array_boost',
    name: 'Coherent Beam Focusing',
    description: 'Phase Arrays produce x2.',
    cost: 200000,
    costResource: 'flux',
    unlockAt: 80000,
    effect: { type: 'generatorMultiplier', targetId: 'array', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'singularity_boost',
    name: 'Event Horizon Polish',
    description: 'Singularity Taps produce x2.',
    cost: 1200000,
    costResource: 'flux',
    unlockAt: 500000,
    effect: { type: 'generatorMultiplier', targetId: 'singularity', value: 2 },
    maxLevel: 1,
    flavorText: 'Yes we polished a black hole. Yes it worked.',
  },
  {
    id: 'rift_boost',
    name: 'Rift Stabilization',
    description: 'Dimensional Rifts produce x2.',
    cost: 8000000,
    costResource: 'flux',
    unlockAt: 3000000,
    effect: { type: 'generatorMultiplier', targetId: 'rift', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'beacon_boost',
    name: 'Signal Amplification',
    description: 'Void Beacons produce x2.',
    cost: 50000000,
    costResource: 'flux',
    unlockAt: 15000000,
    effect: { type: 'generatorMultiplier', targetId: 'beacon', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'global1',
    name: 'Flux Harmonics I',
    description: 'All production x1.5.',
    cost: 8000,
    costResource: 'flux',
    unlockAt: 5000,
    effect: { type: 'globalMultiplier', value: 1.5 },
    maxLevel: 1,
    flavorText: 'Everything vibrates slightly faster now.',
  },
  {
    id: 'global2',
    name: 'Flux Harmonics II',
    description: 'All production x1.5.',
    cost: 150000,
    costResource: 'flux',
    unlockAt: 75000,
    effect: { type: 'globalMultiplier', value: 1.5 },
    maxLevel: 1,
  },
  {
    id: 'global3',
    name: 'Flux Harmonics III',
    description: 'All production x2.',
    cost: 5000000,
    costResource: 'flux',
    unlockAt: 2000000,
    effect: { type: 'globalMultiplier', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'global4',
    name: 'Void Resonance Cascade',
    description: 'All production x3.',
    cost: 200000000,
    costResource: 'flux',
    unlockAt: 80000000,
    effect: { type: 'globalMultiplier', value: 3 },
    maxLevel: 1,
    flavorText: 'The void stopped whispering. It is shouting.',
  },
  {
    id: 'data_boost1',
    name: 'Data Compression',
    description: 'All production x1.25 (costs data).',
    cost: 100,
    costResource: 'data',
    unlockAt: 50000,
    effect: { type: 'globalMultiplier', value: 1.25 },
    maxLevel: 5,
    flavorText: 'Zip it. Zip it good.',
  },
  {
    id: 'data_boost2',
    name: 'Pattern Recognition',
    description: 'x2 click power (costs data).',
    cost: 500,
    costResource: 'data',
    unlockAt: 200000,
    effect: { type: 'clickMultiplier', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'offline1',
    name: 'Dream Processing',
    description: 'Offline efficiency +20%.',
    cost: 2000,
    costResource: 'flux',
    unlockAt: 1000,
    effect: { type: 'offlineEfficiency', value: 0.2 },
    maxLevel: 3,
    flavorText: 'The machine works while you sleep. It prefers it that way.',
  },
  {
    id: 'research_speed1',
    name: 'Accelerated Cognition',
    description: 'Research completes 25% faster.',
    cost: 300,
    costResource: 'data',
    unlockAt: 100000,
    effect: { type: 'researchSpeed', value: 0.25 },
    maxLevel: 3,
  },
  {
    id: 'weaver_boost',
    name: 'Chaos Alignment',
    description: 'Entropy Weavers produce x2.',
    cost: 300000000,
    costResource: 'flux',
    unlockAt: 100000000,
    effect: { type: 'generatorMultiplier', targetId: 'weaver', value: 2 },
    maxLevel: 1,
    flavorText: 'Entropy was already on our side. Now it knows it.',
  },
  {
    id: 'oracle_boost',
    name: 'Paradox Insurance',
    description: 'Temporal Oracles produce x2.',
    cost: 2000000000,
    costResource: 'flux',
    unlockAt: 600000000,
    effect: { type: 'generatorMultiplier', targetId: 'oracle', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'architect_boost',
    name: 'Blueprint Optimization',
    description: 'Reality Architects produce x2.',
    cost: 15000000000,
    costResource: 'flux',
    unlockAt: 5000000000,
    effect: { type: 'generatorMultiplier', targetId: 'architect', value: 2 },
    maxLevel: 1,
  },
  {
    id: 'godengine_boost',
    name: 'Divine Maintenance',
    description: 'The God Engine produces x3.',
    cost: 100000000000,
    costResource: 'flux',
    unlockAt: 30000000000,
    effect: { type: 'generatorMultiplier', targetId: 'godengine', value: 3 },
    maxLevel: 1,
    flavorText: 'Even gods need an oil change.',
  },
  {
    id: 'global5',
    name: 'Universal Constant Tweak',
    description: 'All production x5.',
    cost: 500000000000,
    costResource: 'flux',
    unlockAt: 100000000000,
    effect: { type: 'globalMultiplier', value: 5 },
    maxLevel: 1,
    flavorText: 'We changed π to 3.2. Production went up. Math went down.',
  },
];
